graph LR
A(Matemáticas II)---|"Aula 2.1<br>Telepresencial"|B(Teoría y problemas)
A---|"Telepresencial"|C(Prácticas)
A---D( Aula virtual)
B---E(Bibliografía)
B---F(Relaciones de problemas)
B---G(Guinones de clase)
C---H(Guías de prácticas)
C---I(Material de prácticas)
D---J(Evaluación continua)
D---K(Material de clase)
D---L(fa:fa-database Califiaciones)

